# Generated by Django 5.2.17 on 2026-09-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='support_phone',
            field=models.CharField(default='8592967239', max_length=30),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='whatsapp_number',
            field=models.CharField(default='8592967239', max_length=30),
        ),
    ]
